server:
  port: 9002
spring:
  application:
    name: config
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/LiangCan/YunQiao
eureka:
  client:
    serviceUrl:
      defaultZone: http://dev.honfan.com.cn:9001/eureka/
  instance:
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
    hostname: dev.honfan.com.cn
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}
